version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: probe-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/probe?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - probe-network

  frontend:
    build:
      context: ./my-probe
      dockerfile: Dockerfile
    container_name: probe-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - probe-network

  database:
    image: mysql:8.0
    container_name: probe-database
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=probe
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - probe-network

networks:
  probe-network:
    driver: bridge

volumes:
  mysql-data:
